library(dataRetrieval)
siteNumber <- '040871475'
ParameterCd <- '00045'
StartDate <- '1997-10-01'
EndDate <- '2012-10-01'
outfall_precip <- getRDB1Data("D:/JLTData/gmia/outfall7_precip.rdb",asDateTime=TRUE)
outfall_temp <- getRDB1Data("D:/JLTData/gmia/outfall7comp.rdb",asDateTime=TRUE)
outfall_precip$datetime <- as.POSIXct(paste(outfall_precip$DATE,outfall_precip$TIME,sep=" "),format="%Y%m%d %H%M%S")
outfall_temp$datetime <- as.POSIXct(paste(outfall_temp$DATE,outfall_temp$TIME, sep=" "),format="%Y%m%d %H%M%S")
daily_summ <- read.csv("D:/JLTData/gmia/global_daily_summary_CDO2400066445620.txt",header=TRUE,stringsAsFactors=FALSE,strip.white=TRUE)
daily_summ$FRSHTT <- sprintf("%06d",daily_summ$FRSHTT)
daily_summ$date <- as.Date(as.character(daily_summ$YEARMODA),format="%Y%m%d")
daily_summ$max_flg <- ifelse(substr(daily_summ$MAX,nchar(daily_summ$MAX),nchar(daily_summ$MAX)+1)=='*','*','')
daily_summ$MAX <- ifelse(daily_summ$max_flg=='*',as.numeric(substr(daily_summ$MAX,1,nchar(daily_summ$MAX)-1)),as.numeric(daily_summ$MAX))
daily_summ$min_flg <- ifelse(substr(daily_summ$MIN,nchar(daily_summ$MIN),nchar(daily_summ$MIN)+1)=='*','*','')
daily_summ$MIN <- ifelse(daily_summ$min_flg=='*',as.numeric(substr(daily_summ$MIN,1,nchar(daily_summ$MIN)-1)),as.numeric(daily_summ$MIN))
daily_summ$precip_flg <- ifelse(!is.numeric(substr(daily_summ$PRCP,nchar(daily_summ$PRCP),nchar(daily_summ$PRCP)+1)),substr(daily_summ$PRCP,nchar(daily_summ$PRCP),nchar(daily_summ$PRCP)+1))
daily_summ$PRCP <- ifelse(!is.na(daily_summ$precip_flg),as.numeric(substr(daily_summ$PRCP,1,nchar(daily_summ$PRCP)-1)),as.numeric(daily_summ$PRCP))
daily_summ$TEMP <- ifelse(daily_summ$TEMP==9999.9,'',daily_summ$TEMP)
daily_summ$DEWP <- ifelse(daily_summ$DEWP==9999.9,'',daily_summ$DEWP)
daily_summ$SLP <- ifelse(daily_summ$SLP==9999.9,'',daily_summ$SLP)
daily_summ$STP <- ifelse(daily_summ$STP==9999.9,'',daily_summ$STP)
daily_summ$VISIB <- ifelse(daily_summ$VISIB==999.9,'',daily_summ$VISIB)
daily_summ$WDSP <- ifelse(daily_summ$WDSP==999.9,'',daily_summ$WDSP)
daily_summ$MXSPD <- ifelse(daily_summ$MXSPD==999.9,'',daily_summ$MXSPD)
daily_summ$GUST <- ifelse(daily_summ$GUST==999.9,'',daily_summ$GUST)
daily_summ$MAX <- ifelse(daily_summ$MAX==9999.9,'',daily_summ$MAX)
daily_summ$MIN <- ifelse(daily_summ$MIN==9999.9,'',daily_summ$MIN)
daily_summ$PRCP <- ifelse(daily_summ$PRCP==99.99,'',daily_summ$PRCP)
daily_summ$SNDP <- ifelse(daily_summ$SNDP==999.9,'',daily_summ$SNDP)
daily_summ$fog <- substr(daily_summ$FRSHTT,1,1)
daily_summ$rain <- substr(daily_summ$FRSHTT,2,2)
daily_summ$snow <- substr(daily_summ$FRSHTT,3,3)
daily_summ$hail <- substr(daily_summ$FRSHTT,4,4)
daily_summ$thunder <- substr(daily_summ$FRSHTT,5,5)
daily_summ$tornado <- substr(daily_summ$FRSHTT,6,6)

gmia_hourly_global <- read.delim("D:/JLTData/gmia/hourly_global.txt",stringsAsFactors=FALSE)